### ISSUE TITLE
Update templates with new mat file format for game version 1.48 and above

### ISSUE THREAD

**Issue by Mike7O** [WerewolfCustoms/ModsStudio2IssueBoard#488]
Task List; update following templates:

... ms2 library > models > scsmod > templates ...

- [x] AdvancedTruckSkin
- [x] CargoContainer
- [x] PaintedWheels
- [x] SimpleCargo
- [x] SimpleTruckSkin
- [x] TrailerMudflap
- [x] TrailerMudflapsFront
- [x] TrailerMudflapsRear
- [x] TrailerSkin
- [x] TruckEngine
- [x] TruckLightbox
- [x] TruckMudflaps
- [x] TruckWindscreenDecal

**Describe the bug**
```
ERROR [00004] (/universal/material/ui/accessory/icon.mat): Found non-empty binding beyond the expected ones.
ERROR [00004] (/universal/material/ui/accessory/icon.mat): Found non-empty texture location beyond the expected ones.
```
Because of WU Update 🤨
```
Current Version 1.0.49 (af61694b8c38) - 21.5.2024
Re-enabled texture related checks
```

**To Reproduce**
1. Create a mod
2. Try to upload to Workshop
3. You get those errorlines
4. See error (at the top)

**Expected behavior**
No errors while uploading 😎

**Screenshots**

**what have changed ?**
 **icon.mat** (example...so any name)  in directory **material/ui/accessory**
***from:***
```css
material : "ui"
{
    texture : "icon.tobj"
    texture_name : "texture"
}

```
***to:***
```css
effect : "ui.rfx" {
    texture : "texture" {
        source : "icon.tobj"
        u_address : clamp
        v_address : clamp
        mip_filter : none
    }
}

```
**_To adapt to this new style, how to make MS2 export this so it is possible to upload to Workshop ?_** 

**Desktop (please complete the following information):**
 - Version [e.g. 2024.1] 

**Additional context**
https://discord.com/channels/611134812471820348/1021379459703652362/1242538317661208666
https://discord.com/channels/611134812471820348/611134813021143041/1242554938685395047
